### ISSUE TITLE
Handling of privately kept packages forks

### ISSUE THREAD

**Issue by WTK** [fpgmaas/deptry#114]
**Question**

Should deptry be able to handle private forks of packages kept in private repositories via such entry in requirements.txt: `git+https://github.com/xxxxx/graphene-django-optimizer@161d4cd5f177ef1ab4a5398727c01c13f824e296#egg=graphene-django-optimizer`?

Currently I get "Could not parse dependency name from url" error for such entries.

**Comment by fpgmaas** [comment]
Thanks for your question. I added parsing of these urls in release 5.0.1.
