### ISSUE TITLE
Handle multiple non-dev requirements files

### ISSUE THREAD

**Issue by mkniewallner** [fpgmaas/deptry#137]
**Is your feature request related to a problem? Please describe.**

Right now, it's possible to pass multiple requirements files for dev dependencies, through `--requirements-txt-dev`, but it's not possible to do so for non-dev dependencies.

It's usually more common to have multiple dev dependencies files, so the current behaviour is not unreasonable, but there are situations where even non-dev requirements can be separated over multiple requirements files (for instance, by having a file for public dependencies from PyPI, and another one for private ones in a custom registry).

**Describe the solution you would like**

By adapting a bit the code, we could make it possible to pass multiple non-dev requirements files, while still allowing to pass a single one if needed (similarly to the behaviour of `--requirements-txt-dev`). This would allow flexibility for edgy use-cases, while keeping a sensible and most likely convenient default for most usages.

**Additional context**

If you think that the request makes sense, I would be more than happy to make a PR implementing the change, just let me know.

**Comment by fpgmaas** [comment]
I think this makes sense! If you have the time, feel free to create the PR.
