### ISSUE TITLE
Add PEP-582 support: __pypackages__ directory

### ISSUE THREAD

**Issue by fpgmaas** [fpgmaas/deptry#158]
**Is your feature request related to a problem? Please describe.**

https://peps.python.org/pep-0582/

**Comment by mkniewallner** [comment]
As the PEP is still in a draft state and stalled, and the discussion about the architecture is still open, I would personally be a bit hesitant to add support for this PEP, but if you think that it's worth adding it, I'm not against it.

**Comment by fpgmaas** [comment]
I think you are right and it's worth waiting to see if the PEP will be implemented.

**Comment by iamthen0ise** [comment]
Unfortunately, is says that PEP was rejected https://discuss.python.org/t/pep-582-python-local-packages-directory/963/430
