### ISSUE TITLE
Merge configuration through CLI and `pyproject.toml` documentations into a single page

### ISSUE THREAD

**Issue by mkniewallner** [fpgmaas/deptry#249]
**Is your feature request related to a problem? Please describe.**

Right now, the configuration options documentation is split across 2 different pages:

- https://github.com/fpgmaas/deptry/blob/0.7.0/docs/usage.md that shows the options that can be set through the CLI, and details what the options do
- https://github.com/fpgmaas/deptry/blob/0.7.0/docs/pyproject-toml.md that shows the options that can be set in `pyproject.toml`, without details about what they do

This might be a bit confusing, especially for first-time users.

**Describe the solution you would like**

A single page detailing all the options, and for each of them:

- the default
- the parameter name through the CLI
- the parameter name in `pyproject.toml`
- example usages
- details about what the option does

might be a better way to convey the possible configuration options.

I find [`isort`'s documentation](https://pycqa.github.io/isort/docs/configuration/options.html) to be a really good example of a good way to showcase everything from a single page.

**Comment by fpgmaas** [comment]
I agree that `isort`'s documentation is clearer than `deptry`'s. Let's change it to match their style.

As we say in Dutch; 'Beter goed gestolen dan slecht bedacht', which loosely translates to "better stolen well than badly conceived" 😄
