### ISSUE TITLE
Shouldn't this be `poetry` instead of `pdm`?

### ISSUE THREAD

**Issue by baggiponte** [fpgmaas/deptry#293]
Hello, just saw this running the `-v` option:

```
pyproject.toml found!
pyproject.toml does not contain a [tool.poetry.dependencies] section, so PDM is not used to specify the project's dependencies.
pyproject.toml contains a [tool.pdm.dev-dependencies] section, so PDM is used to specify the project's dependencies.
```

Shouldn't this be "so Poetry is not used"?

https://github.com/fpgmaas/deptry/blob/3d4f724077121a8417f7d356e25888161b27af07/deptry/dependency_specification_detector.py#L67

**Comment by mkniewallner** [comment]
Indeed, that's definitely an oversight, thanks for spotting that.

If you are willing to make a pull request to fix that, will gladly review it, otherwise will fix that at a later time.

**Comment by baggiponte** [comment]
Would love to!
