### ISSUE TITLE
Optional dependencies not marked as optional

### ISSUE THREAD

**Issue by akeeman** [fpgmaas/deptry#334]
**Describe the bug**

Maybe I'm wrong, but as I read it some dependencies should have been marked optional while they're not, when using pep621 (or pdm):

https://github.com/fpgmaas/deptry/blob/2f39fb59da3b89cd08499faf0aecdd8b058455d6/tests/dependency_getter/test_pep_621.py#L20-L27

foobar:
https://github.com/fpgmaas/deptry/blob/2f39fb59da3b89cd08499faf0aecdd8b058455d6/tests/dependency_getter/test_pep_621.py#L60

barfoo:
https://github.com/fpgmaas/deptry/blob/2f39fb59da3b89cd08499faf0aecdd8b058455d6/tests/dependency_getter/test_pep_621.py#L65

dep:
https://github.com/fpgmaas/deptry/blob/2f39fb59da3b89cd08499faf0aecdd8b058455d6/tests/dependency_getter/test_pep_621.py#L70

**Comment by fpgmaas** [comment]
Good find. This is a consequence of lack of standardization within the Python ecosystem/PEP-621. PEP-621 does not specify a way to list development dependencies, and just places everything under optional dependencies. See e.g. [here](https://peps.python.org/pep-0621/#example). So for optional dependencies, we use the definition as listed [here](https://setuptools.pypa.io/en/latest/userguide/dependency_management.html#optional-dependencies). It is done by [this](https://github.com/fpgmaas/deptry/blob/main/deptry/dependency_getter/pep_621.py#L84) part of the code.

**Comment by akeeman** [comment]
Ok, I wasn't aware that it was intentional.
