### ISSUE TITLE
Drop support for Python 3.7

### ISSUE THREAD

**Issue by mkniewallner** [fpgmaas/deptry#351]
**Is your feature request related to a problem? Please describe.**

Python 3.7 support will reach end of life [on 2023-06-27](https://devguide.python.org/versions/), so we could drop support in `deptry` around the same date.

**Describe the solution you would like**

Requiring `python >= 3.7` in the project definition, bumping the minimum version for development tools we use in the codebase (`black`, `Ruff`, `mypy`, ...), and removing custom code and dependencies needed to support Python 3.7.

**Additional context**

According to PyPI stats, we don't seem to have a lot of users on Python 3.7 (and it's entirely possible that the only usage comes from our own test suite running on the CI):

```shell
$ pipx run pypistats python_minor deptry --last-month -f markdown
```

| category | percent | downloads |
|:---------|--------:|----------:|
| null     |  85.37% |    22,770 |
| 3.10     |   4.68% |     1,248 |
| 3.8      |   4.09% |     1,090 |
| 3.9      |   3.68% |       981 |
| 3.11     |   1.51% |       403 |
| 3.7      |   0.68% |       181 |
| Total    |         |    26,673 |

Date range: 2023-04-01 - 2023-04-30

So maybe we can consider dropping support before Python 3.7 is officially end of life?

**Comment by fpgmaas** [comment]
I think it makes sense to drop support for 3.7 for any of the upcoming releases. Maybe nice to add to the [0.9.0](https://github.com/fpgmaas/deptry/issues/355) release?

**Comment by mkniewallner** [comment]
> I think it makes sense to drop support for 3.7 for any of the upcoming releases. Maybe nice to add to the [0.9.0](https://github.com/fpgmaas/deptry/issues/355) release?

I was originally thinking that we could warn in the changelog of 0.9.0 that this will be the last release supporting 0.9.0, then effectively drop it in 0.10.0, but given the low (or even inexistant) usage of 3.7, let's drop it in 0.9.0.
