### ISSUE TITLE
Determine naming convention for issues/violations/errors/checks

### ISSUE THREAD

**Issue by fpgmaas** [fpgmaas/deptry#404]
**Question**

Right now, we use a combination of the words issue, violation, check, error code. It would be good to determine a standard naming convention. My proposal would be to use "rule" to refer to DEP001, DEP002, etc. and "violation"(as already implemented in the code by @mkniewallner) to refer to specific violations in the code/configuration files.

**Comment by mkniewallner** [comment]
Agree, we should be more consistent in our naming. I must say that we didn't really discuss if "violation" is what we want to go with when starting using that over the codebase, but I think that it goes well with the usage of "rule" (at least compared to using "issue"), so using "rule" and "violation" is something I would agree with.

**Comment by fpgmaas** [comment]
If we go for 'rule' and 'violation', we need to make some small changes. For example, a 'missing dependency' is an issue, whereas 'Project should not contain missing dependencies' is a rule that can be violated. So e.g. in the docs, we'd replace this:

```
- [Missing dependencies (DEP001)](#missing-dependencies-dep001)
- [Unused dependencies (DEP002)](#unused-dependencies-dep002)
- [Transitive dependencies (DEP003)](#transitive-dependencies-dep003)
- [Misplaced development dependencies (DEP004)](#misplaced-development-dependencies-dep004)
```

with

```
| Code   | Description                        | More information                                    |
|--------|------------------------------------| ----------------------------------------------------|
| DEP001 | Project should not contain missing dependencies               | [link](#missing-dependencies-dep001)                |
| DEP002 | Project should not contain unused dependencies               | [link](#unused-dependencies-dep002)                 |
| DEP003 | Project should not contain unnecessary transitive dependencies            | [link](#transitive-dependencies-dep003)             |
| DEP004 | Project should not use development dependencies in non-development code | [link](#misplaced-development-dependencies-dep004)  |
```

see [here](https://github.com/fpgmaas/deptry/pull/402/files#diff-0a763d6c876e7f51f0439a2a78e17249677734497d33e8dd0268548e05c9818d).

**Comment by fpgmaas** [comment]
Going for "rule" and "violation".
