### ISSUE TITLE
Add the option to check the current version

### ISSUE THREAD

**Issue by lisphilar** [fpgmaas/deptry#41]
**Is your feature request related to a problem? Please describe.**

Because `deptry` has many released versions, users need to confirm the current version number frequently.

**Describe the solution you would like**

Option to check the current version `deptry --version` will be helpful.

**Additional context**

At this time, we need check the current version with poetry.lock etc.

**Comment by fpgmaas** [comment]
Great idea! Will investigate this soon.

**Comment by lisphilar** [comment]
Thank you for your consideration!
We ma need to add both of  `deptry.__version__`  and version description of pyproject.toml file. If I remember right, poetry prohibits pyproject.toml reading objects of .py files.

Additonally, the current version description was 0.1.0 (< 0.2.3).
https://github.com/fpgmaas/deptry/blob/8af1cfc7588f59ac495653b51f295e2d50d49842/pyproject.toml#L3
