### ISSUE TITLE
Add option to only include certain directories, instead of excluding many.

### ISSUE THREAD

**Issue by fpgmaas** [fpgmaas/deptry#49]
**Is your feature request related to a problem? Please describe.**

Right now, by default every directory is scanned, and directories can be ignored with `--ignore-directories`. This can be cumbersome when there are many directories with py files.

**Describe the solution you would like**

It would be nice to give the user the option to instead use an argument to include some directories, and have all others ignored by default.

**Comment by lisphilar** [comment]
Sorry to bother you, but it will be great to have "--include" option because 23.3 s -> 0.1 s in my case.
(current directory: https://github.com/lisphilar/covid19-sir)

```Python
import time
from pathlib import Path

def _time(func, *args, **kwargs):
    start = time.time()
    results = list(func(*args, **kwargs))
    print(f"{time.time() - start:.1f} s")
    return results

# 23.3 s
_time(Path().rglob, "*.py")

# 0.1 s
_time(Path("covsirphy/").rglob, "*.py")
```

I will create a pull request to update the follwing files if effective and acceptable.
- https://github.com/fpgmaas/deptry/blob/main/deptry/python_file_finder.py
- https://github.com/fpgmaas/deptry/blob/main/deptry/cli.py

**Comment by fpgmaas** [comment]
Thanks for your contribution, definitely no need to apologise! I was aware that my method of listing files was a bit slow, but I was not aware it was this slow. I am currently working on https://github.com/fpgmaas/deptry/issues/55 and https://github.com/fpgmaas/deptry/issues/3, that should be done within a couple of days and should already show a great improvement in speed. I will pick up this issue next, so I expect it should be done by the end of the upcoming week.

**Comment by lisphilar** [comment]
Thank you for your work! I will follow #55 and #3.

**Comment by fpgmaas** [comment]
@lisphilar Could you check with release 0.5.0? I tried it locally on covid19-sir and the run time seems to have improved drastically:

```zsh
$ time deptry .                    
Scanning 118 files...
Success! No obsolete, missing, or transitive dependencies found.
deptry .  0.35s user 0.13s system 77% cpu 0.617 total
```

**Comment by lisphilar** [comment]
Thank you!!
I confirmed it was quite improved and `covsirphy` will use `deptry` version 0.5.0 with https://github.com/lisphilar/covid19-sir/issues/1207.

**Comment by fpgmaas** [comment]
Closing this for now, as the current implementation of the location argument `ROOT`and the `exclude` and `extend-exclude` arguments should be able to cover all cases.
