### ISSUE TITLE
A way to exclude packages in requirements.txt

### ISSUE THREAD

**Issue by jkugler** [fpgmaas/deptry#546]
I found this section of the documentation: https://fpgmaas.github.io/deptry/usage/#per-check-ignores This provides ways to ignore packages in pyproject.toml or the CLI. It would be nice to be able to do that in requirements.txt as.

**Describe the solution you would like**

In our case, we have optional dependencies for fastapi; `python-multipart` in this case, but fastapi doesn't directly rely on them, generating an error. It would be nice to do something like this:
```
python-multipart==0.0.6 #deptry: no DEP002
or
python-multipart==0.0.6 #deptry: -DEP002
```
or some similar to exclude it from the checks.

Thanks for a spiffy project!

**Comment by mkniewallner** [comment]
Hi, just to make sure I'm not missing something, is there something that currently prevents you from specifying the packages to ignore in `pyproject.toml`, apart from maybe not currently having a `pyproject.toml` file in your project?

I don't think that this is something we want to add support for, as this requires to parse comments in requirements files, which would be yet another way to configure the tool alongside `[tool.deptry]` and CLI options.

**Comment by jkugler** [comment]
Correct, we do not currently have a pyproject.toml. Thanks for checking in, though!
