### ISSUE TITLE
Have the --exclude (and potentially --include when it's added) arguments work with regex.

### ISSUE THREAD

**Issue by fpgmaas** [fpgmaas/deptry#55]
**Is your feature request related to a problem? Please describe.**

Currently, the --exclude argument only checks for directories and files that start with elements of the list that is provided.

**Describe the solution you would like**

It would be great to have this also work with pattern matching. e.g. the user can provide `--exclude test*` and all directories that match that pattern will be excluded. 

**Additional context**

Similar for `--include`, if it were to be added (https://github.com/fpgmaas/deptry/issues/49)

**Comment by WTK** [comment]
Basically all of the cli options could support patterns if possible.

**Comment by fpgmaas** [comment]
Thanks for your comment and voting for this issue. I think I will make this my next issue to work on.

With regards to the regex patrerns for other cli arguments; do you have a specific use case for this, or is this more a nice to have? For now the other CLI arguments affected would be `ignore_obsolete`, `ignore_missing`, `ignore_misplaced_dev`, `ignore_transitive` and `requirements_txt_dev`. I do not see regex patterns being useful for the last one. For the `ignore_` arguments, it seems a bit redundant to me;  would it not be an indication of other problems if a regex is required/helpful to ignore dependency issues?

**Comment by WTK** [comment]
Thanks for picking it up. Yeah, I was a bit too easy with saying "all cli options". What I meant was that it would be useful to be able to use patterns whenever you can specify directories and/or files. I'd rather see cli use glob https://docs.python.org/3/library/glob.html rather than regexp as the former is tailored specifically to handle files and directories structure.

**Comment by fpgmaas** [comment]
I have added support for regex patterns in release `0.5.0`. The following statements are equivalent:

```
deptry . -e bar -e ".*/foo/"
deptry . --exclude "bar|.*/foo/"
```

See also [the updated documentation](https://fpgmaas.github.io/deptry/usage/#excluding-files-and-directories).

I will make sure the `--include` flag works similarly, once it is added.
