### ISSUE TITLE
Provide wheel files for versions of Python beyond 3.8

### ISSUE THREAD

**Issue by nathanjmcdougall** [fpgmaas/deptry#590]
As of version v0.14.0, the wheel files are platform dependent. The uploaded wheels on PyPI are restricted to Python 3.8. I would like to be able to use pre-built wheels for Python 3.10 and 3.11.

**Comment by mkniewallner** [comment]
Hi, the wheels use [ABI3](https://pyo3.rs/v0.14.5/features.html#abi3-py36--abi3-py37--abi3-py38--abi3-py39) to define the minimum Python version supported, so they should also be selected by your package manager when using Python >= 3.8.

Could you share more details on your setup? OS, architecture (x86 or ARM), package manager you use, ...)?

**Comment by nathanjmcdougall** [comment]
Apologies, I didn't investigate this hard enough and have misdiagnosed things. The wheels were downloading perfectly fine using `pip` from PyPI.

The issue was actually with using `pre-commit` which clones the repo and then attempts to build locally with `python -mpip install .` I didn't realize this - I was assuming it was using PyPI and it attempted a build because it was missing compatible wheel files.

I think I will open a separate issue for updating the docs with an alternative pre-commit configuration which runs `deptry` in the local environment.
