### ISSUE TITLE
Licence Metadata appears to be missing from pypi

### ISSUE THREAD

**Issue by jonathanrainer** [fpgmaas/deptry#623]
**Describe the bug**

Up to an including v0.13.0 the licence on `pypi` was correct with reference to the repo itself, i.e. MIT Licence. However from v0.14.0 onwards this is not the case. This can be seen if you inspect the releases page for v0.13.0 on `pypi` as compared to v0.14.0. This is probably something really simple but if it could be resolved that would be brilliant because this is causing `deptry` to flag as unlicensed in security tooling.

**To Reproduce**

1. Head to https://pypi.org/project/deptry/0.13.0/, observe that in the left hand sidebar itself lists `License: MIT License (MIT)`
2. Head to https://pypi.org/project/deptry/0.14.0/, observe that in the left hand sidebar there is no License entry.

**Expected behavior**

The licence listing would continue between versions as it has not changed.

**Additional context**

Thank you so much for making a tool like `deptry` that is so cool and useful, I hope this can be fixed quickly :)

**Comment by mkniewallner** [comment]
Thanks for your report! It looks like Poetry [sets that automatically](https://python-poetry.org/docs/pyproject#classifiers), so we lost that information when switching over PDM. Will add the classifier manually.

**Comment by mkniewallner** [comment]
[0.14.2](https://pypi.org/project/deptry/0.14.2/) has been released with the proper classifier. Thanks again for the report, appreciate it!

**Comment by jonathanrainer** [comment]
@mkniewallner thanks for being so responsive! I really love deptry so I’m glad I can now use it without tripping our security tooling. Thanks again for acting so quickly!
