### ISSUE TITLE
Downgrade click to (>=8.0.0,<9.0.0)

### ISSUE THREAD

**Issue by AleksandrLiadov** [fpgmaas/deptry#64]
Hello,

Could you safely downgrade click to (>=8.0.0,<9.0.0)?

Your click version is too recent, it makes impossible to install it to pyproject which has old packages ( from 2021 ).

**Comment by fpgmaas** [comment]
I will see if I can relax the requirement. I see that `black` also has a more 'click = "^8.0.0"' as requirement: https://github.com/psf/black/blob/main/setup.py

Will get back to you on this ASAP

**Comment by AleksandrLiadov** [comment]
@fpgmaas thanks for your quick response!
Really great tool!

**Comment by fpgmaas** [comment]
@AleksandrLiadov Thanks for the compliment, and thanks for contributing to the project. I appreciate the feedback :) 

This issue should now be fixed with release [0.2.14](https://github.com/fpgmaas/deptry/releases/tag/0.2.14). Could you let me know if this works for you? Thanks!
