### ISSUE TITLE
Ignore 'TYPE_CHECKING' imports if string annotation is used

### ISSUE THREAD

**Issue by Zer0x00** [fpgmaas/deptry#661]
The latest release did include [a feature](https://github.com/fpgmaas/deptry/pull/652) to skip type checking blocks. (Thanks for it!)

Currently it works only if it finds the `TYPE_CHECKING` block in combination with `from __future__ import annotations`.
But as far as my understanding goes it is also perfectly fine to not have the annotations module imported but annotate them as a string like this:

```python3
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from aws_lambda_powertools.utilities.data_classes import SQSEvent

def handle_sqs_event(event: 'SQSEvent', _context)
   ...
```

deptry currently doesn't respect those cases.

**Comment by mkniewallner** [comment]
Thanks for the report. Indeed, this is an oversight from me. This should be fixed with https://github.com/fpgmaas/deptry/pull/662.
