### ISSUE TITLE
Documentation error: missing quotation marks for --per-rule-ignores

### ISSUE THREAD

**Issue by burgikukac** [fpgmaas/deptry#673]
**Describe the bug**

On the https://deptry.com/usage/ page, [Per rule ignores](https://deptry.com/usage/#per-rule-ignores) part, the CLI example you provide this example:
`deptry . --per-rule-ignores DEP001=matplotlib,DEP002=pandas|numpy`

I think that because of the pipe symbol, the usage of quotation marks is needed, like in the 'Exclude' or 'Extended Exclude' parts of the docs.

Thank you for your work!

**Comment by mkniewallner** [comment]
Thanks for the report!
