### ISSUE TITLE
CI integration (--check option)

### ISSUE THREAD

**Issue by AleksandrLiadov** [fpgmaas/deptry#72]
Could we have an option for CI?
Example: `deptry --check  .` 
If it has done already, where I can find an example of CI integration?

**Comment by fpgmaas** [comment]
This should be simply

```
deptry .
```

It will return exit code `1` if issues are found, and exit code `0` if no errors are found.

Does this answer your question? I realise this is not specified in the documentation, I will see how to incorporate this information there.

**Comment by AleksandrLiadov** [comment]
Yes thank you, I will test with Gitlab CI!
