### ISSUE TITLE
Transitive dependency was reported as a missing dependency

### ISSUE THREAD

**Issue by Willa1228** [fpgmaas/deptry#784]
**Describe the bug**

I encountered this problem while working on my project. Since the project dependencies are a bit too complicated, I tried a simpler case and still found an issue.  if my project has a dependency on package A, which internally depends on package B, Deptry should recognize package B as a transitive dependency. However, it incorrectly reports package B as a missing dependency.

For example, in my requirements.txt, I have included flask-sqlalchemy, which depends on flask. When I run Deptry, it does not recognize that flask is installed as a dependency of flask-sqlalchemy. Consequently, when my project imports flask, Deptry reports an error stating that flask is not listed in the requirements.

**To Reproduce**

1. add flask-sqlalchemy into my requirements
2. import flask in my code
3. deptry .

**System [please complete the following information]:**

-   OS: Mac OS
-   Language Version: Python 3.11

**Comment by mkniewallner** [comment]
How do you run `deptry`? In the same virtual environment where dependencies are installed?

If not, that would explain the issue, since to know which dependencies are transitive, `deptry` needs to have access to the dependencies installed in the virtual environment holding your project dependencies, as mentioned [in the documentation](https://deptry.com/#installation).

For instance trying to reproduce your issue, if I run `deptry` from a virtual environment holding project dependencies:
```shell
$ python -m venv .venv
$ source .venv/bin/activate.fish
$ pip install -r requirements.txt
$ pip install deptry==0.17.0
```

I'll get:
```console
$ deptry .
Scanning 1 file...

foo.py:1:8: DEP003 'flask' imported but it is a transitive dependency
requirements.txt: DEP002 'flask-sqlalchemy' defined as a dependency but not used in the codebase
Found 2 dependency issues.
```

But if exiting the virtual environment:
```console
$ pipx run deptry .
Assuming the corresponding module name of package 'flask-sqlalchemy' is 'flask_sqlalchemy'. Install the package or configure a package_module_name_map entry to override this behaviour.
Scanning 1 file...

foo.py:1:8: DEP001 'flask' imported but missing from the dependency definitions
requirements.txt: DEP002 'flask-sqlalchemy' defined as a dependency but not used in the codebase
Found 2 dependency issues.
```

**Comment by jorisgu** [comment]
@Willa1228 , this is the intended behavior.
flask-sqlalchemy could "someday" be independant of `flask`. It is not a likely scenario of course but the idea is still true.
So if you `import flask` in your code, you should not rely on flask-sqlalchemy to depend on it. You should instead add it to your deps explicitely.
