### ISSUE TITLE
`.gitignore` from parent git repository is used while it shouldn't

### ISSUE THREAD

**Issue by fry69** [fpgmaas/deptry#882]
My setup may be not exactly standard, but `deptry` is the only tool that has a problem with it:

Up in my filesystem hierarchy there lingers a Git repository which ignores everything (`*`) and only a few files/directories are excluded from this catch all ignore. This works 100% fine with VSCode Git, command line Git and every other Git related tool I can think of.

Only `deptry` refuses to find any file with this setup, as it somehow climbs up in hierarchy to find my `.gitignore`->
```
Scanning 0 file...
```
Is there a way to fix this gracefully?

**Comment by mkniewallner** [comment]
Agree that we should avoid reading `.gitignore` from parents directories outside the path where `deptry` is invoked. We could disable [parents](https://docs.rs/ignore/0.4.23/ignore/struct.WalkBuilder.html#method.parents) when constructing the directory iterator [here](https://github.com/fpgmaas/deptry/blob/5f407ad2638f60ddd2a8999010d649f8fd4ad986/src/python_file_finder.rs#L62-L68).

But testing a bit the changes, this made me realise that we probably don't handle `.gitignore` properly today. If we disable reading parents, given the following structure:

```
.
├── requirements.txt
└── src
    └── foo.py
```
where `.gitignore` contains `*`.

```console
$ deptry .
[...]
Scanning 0 file...
[...]
```

```console
$ deptry src
[...]
Scanning 1 file...
[...]
```

Reading `.gitignore` file is relative to the directory passed as a positional argument, which is probably not what we want. Seems to me that reading the file from the location `deptry` itself is invoked would make more sense, although we should likely also respect `.gitignore` in sub-directories (which is probably something that the library we use does automatically).

**Comment by fry69** [comment]
Tiny addition: There must be some kind clever library at work, as even if I move the git ignore patterns from `.gitignore` to `.git/info/exclude`, they get still get found in the git repository up in the parent hierarchy.

**Comment by mkniewallner** [comment]
Implemented changes in https://github.com/fpgmaas/deptry/pull/908 that should prevent `deptry` from finding parent `.gitignore` in your use case. If you have Rust and [uv](https://docs.astral.sh/uv/) on your system, you should be able to test this with:

```shell
uvx \
  --from git+https://github.com/fpgmaas/deptry@4217bf7bee14f7558f9ad5f22f215f5703ac4f4b \
  deptry .
```

(since this won't install dependencies in your project, you'll probably have many errors, but this should still show if files are now scanned or not)
