### ISSUE TITLE
musllinux wheel

### ISSUE THREAD

**Issue by threonate** [fpgmaas/deptry#977]
Would you consider shipping a musllinux wheel? This is possible since [PEP 656](https://www.python.org/dev/peps/pep-0656/).

It would be great to have the wheel on PyPI for Docker containers running Alpine, which some people use in their CI/CD.

Thank you!

**Comment by mkniewallner** [comment]
With [0.21.2](https://github.com/fpgmaas/deptry/releases/tag/0.21.2), wheels are now provided for musllinux.

**Comment by threonate** [comment]
Merci!
